== Die ersten Grafikbefehle

=== Das lernst du

In diesem Kapitel lernst du:

* den Bildschirm zu löschen
* einzelne Pixel zu setzen
* Linien zu zeichnen
* Koordinaten zu verwenden
* Grafiken mit Schleifen und Zufallszahlen zu erzeugen
* wie das Konzept der Turtle-Grafik funktioniert

Am Ende des Kapitels kannst du eigene einfache Zeichnungen erstellen.

=== Endlich wird gezeichnet

In den bisherigen Kapiteln haben wir hauptsächlich mit Texten gearbeitet.

Nun beginnen wir mit der eigentlichen Grafikprogrammierung.

Die wichtigsten Befehle für den Einstieg sind:

* CLS
* PIXEL
* LINE

=== Den Bildschirm löschen

Mit CLS wird der Bildschirm gelöscht.

[source,basic]
----
CLS
----

Der gesamte Bildschirm wird dabei mit der aktuellen Hintergrundfarbe gefüllt.

Es kann auch direkt eine Farbe angegeben werden.

[source,basic]
----
CLS RGB(BLACK)
----

=== Ein einzelner Pixel

Der einfachste Grafikbefehl ist PIXEL.

[source,basic]
----
PIXEL 100,100
----

Dieser Befehl setzt einen einzelnen Bildpunkt an der Position X=100 und Y=100.

=== Ein farbiger Pixel

Natürlich kann auch eine Farbe angegeben werden.

[source,basic]
----
PIXEL 100,100,RGB(RED)
----

=== Unser erstes Grafikprogramm

[source,basic]
----
CLS RGB(BLACK)

PIXEL 100,100,RGB(RED)
----

Das Ergebnis ist ein einzelner roter Punkt auf schwarzem Hintergrund.

=== Mehrere Pixel zeichnen

[source,basic]
----
CLS RGB(BLACK)

PIXEL 100,100,RGB(RED)
PIXEL 101,100,RGB(RED)
PIXEL 102,100,RGB(RED)
PIXEL 103,100,RGB(RED)
PIXEL 104,100,RGB(RED)
----

Aus einzelnen Pixeln entstehen später Linien, Kreise und Bilder.

=== Linien zeichnen

Mit LINE wird eine Linie zwischen zwei Punkten gezeichnet.

[source,basic]
----
LINE X1,Y1,X2,Y2
----

Beispiel:

[source,basic]
----
LINE 10,10,200,10
----

=== Horizontale Linien

[source,basic]
----
CLS

LINE 10,50,200,50
----

Die Linie beginnt bei X=10 und endet bei X=200.

Die Y-Koordinate bleibt konstant.

=== Vertikale Linien

[source,basic]
----
CLS

LINE 100,20,100,200
----

Diesmal bleibt die X-Koordinate konstant.

=== Diagonale Linien

[source,basic]
----
CLS

LINE 10,10,200,150
----

Nun werden sowohl X als auch Y verändert.

=== Linienfarben

Auch für Linien kann eine Farbe angegeben werden.

[source,basic]
----
LINE 10,10,200,100,,RGB(RED)
----

=== Mehrere Linien kombinieren

Mit mehreren Linien können einfache Formen erzeugt werden.

[source,basic]
----
CLS

LINE 50,100,250,100
LINE 150,20,150,180
----

Das Ergebnis ist ein Kreuz.

=== Ein Dreieck zeichnen

[source,basic]
----
CLS

LINE 100,50,50,150
LINE 50,150,150,150
LINE 150,150,100,50
----

=== Ein Haus zeichnen

Mit einigen wenigen Linien lässt sich bereits ein kleines Haus darstellen.

[source,basic]
----
CLS

LINE 50,150,150,150
LINE 150,150,150,80
LINE 150,80,50,80
LINE 50,80,50,150

LINE 50,80,100,30
LINE 100,30,150,80
----

=== Das Haus vom Nikolaus

Eine bekannte Zeichenübung ist das Haus vom Nikolaus.

Versuche, es selbst mit LINE zu zeichnen.

[source]
----
      /\
     /  \
    /____\
    |    |
    | /\ |
    |/  \|
    ------
----

=== Bildschirmmitte berechnen

Mit MM.HRES und MM.VRES lässt sich die Bildschirmmitte berechnen.

[source,basic]
----
MITTEX=MM.HRES/2
MITTEY=MM.VRES/2

PIXEL MITTEX,MITTEY,RGB(RED)
----

Dadurch funktioniert das Programm auf unterschiedlichen Bildschirmgrößen.

=== Ein Fadenkreuz zeichnen

[source,basic]
----
CLS

LINE MM.HRES/2,0,MM.HRES/2,MM.VRES

LINE 0,MM.VRES/2,MM.HRES,MM.VRES/2
----

Dieses Programm zeichnet ein Fadenkreuz durch die Bildschirmmitte.

=== Ein kleines Grafik-Testprogramm

Zum Abschluss verbinden wir die bisher kennengelernten Grafikbefehle mit Schleifen, Zufallszahlen und Farben.

Das folgende Programm zeichnet nacheinander:

* 1000 zufällig verteilte Punkte
* 1000 Kreise
* 1000 Rechtecke

Position, Größe und Farbe werden jeweils zufällig bestimmt.

[source,basic]
----
CLS RGB(BLACK)

PRINT "1000 zufaellige Punkte"

FOR I=1 TO 1000

  X=INT(RND*MM.HRES)
  Y=INT(RND*MM.VRES)

  FARBE=RGB(INT(RND*256),INT(RND*256),INT(RND*256))

  PIXEL X,Y,FARBE

NEXT I

PAUSE 1000


PRINT "1000 zufaellige Kreise"

FOR I=1 TO 1000

  RADIUS=INT(RND*20)+2

  X=INT(RND*(MM.HRES-2*RADIUS))+RADIUS
  Y=INT(RND*(MM.VRES-2*RADIUS))+RADIUS

  FARBE=RGB(INT(RND*256),INT(RND*256),INT(RND*256))

  CIRCLE X,Y,RADIUS,1,1,FARBE

NEXT I

PAUSE 1000


PRINT "1000 zufaellige Rechtecke"

FOR I=1 TO 1000

  BREITE=INT(RND*50)+5
  HOEHE=INT(RND*50)+5

  X=INT(RND*(MM.HRES-BREITE))
  Y=INT(RND*(MM.VRES-HOEHE))

  FARBE=RGB(INT(RND*256),INT(RND*256),INT(RND*256))

  BOX X,Y,BREITE,HOEHE,1,FARBE

NEXT I
----

=== Das Programm verstehen

Für jedes Grafikelement werden zunächst zufällige Bildschirmkoordinaten berechnet.

[source,basic]
----
X=INT(RND*MM.HRES)
Y=INT(RND*MM.VRES)
----

Dadurch werden nur Positionen innerhalb der aktuellen Bildschirmauflösung erzeugt.

Auch die Farbe wird zufällig zusammengesetzt:

[source,basic]
----
FARBE=RGB(INT(RND*256),INT(RND*256),INT(RND*256))
----

Jeder der drei Farbanteile Rot, Grün und Blau erhält einen zufälligen Wert zwischen 0 und 255.

Bei Kreisen wird zusätzlich ein zufälliger Radius bestimmt:

[source,basic]
----
RADIUS=INT(RND*20)+2
----

Die Berechnung der Position berücksichtigt den Radius. Dadurch wird verhindert, dass der Mittelpunkt eines Kreises zu nahe am Bildschirmrand liegt.

Bei den Rechtecken werden Breite und Höhe ebenfalls zufällig erzeugt:

[source,basic]
----
BREITE=INT(RND*50)+5
HOEHE=INT(RND*50)+5
----

Die beiden `PAUSE`-Anweisungen sorgen für eine kurze Unterbrechung zwischen den drei Abschnitten.

[TIP]
====
Da die Grafikelemente nicht gelöscht werden, überlagern sich Punkte, Kreise und Rechtecke zunehmend.

Möchtest du jeden Test auf einem leeren Bildschirm sehen, füge vor dem jeweiligen Abschnitt eine weitere Anweisung ein:

[source,basic]
----
CLS RGB(BLACK)
----
====

=== Probier's selbst!

Versuche folgende Aufgaben:

. Zeichne ein Quadrat aus vier Linien.
. Zeichne einen Stern.
. Zeichne ein eigenes Haus.
. Zeichne ein Spielfeld für Tic-Tac-Toe.
. Zeichne die Umrisse eines Briefumschlags.

=== Experimentiere!

Probiere folgende Änderungen aus:

* Verwende andere Farben.
* Zeichne ein größeres Haus.
* Zeichne mehrere Dreiecke.
* Zeichne ein Gitter aus Linien.

=== Turtle-Grafik

In den bisherigen Beispielen haben wir Linien gezeichnet, indem wir ihre Anfangs- und Endpunkte angegeben haben.

Es gibt jedoch noch eine andere Möglichkeit, Grafiken zu erzeugen.

Stell dir vor, auf dem Bildschirm befindet sich eine kleine Schildkröte. Sie kennt ihre aktuelle Position und ihre Blickrichtung.

Sie kann nur drei Dinge tun:

* vorwärts laufen
* sich nach links drehen
* sich nach rechts drehen

Während sie sich bewegt, zeichnet sie eine Linie.

Auf diese Weise entstehen nach und nach geometrische Figuren.

[NOTE]
.Geschichte
====
Die Turtle-Grafik wurde Ende der 1960er-Jahre von **Seymour Papert** im Zusammenhang mit der Programmiersprache **LOGO** entwickelt.

Anstatt Koordinaten und mathematische Formeln in den Mittelpunkt zu stellen, sollten Kinder spielerisch lernen, wie Programme aufgebaut sind. Die kleine "Schildkröte" machte das Ergebnis jedes Befehls sofort sichtbar.

Viele Programmierer kamen auf diese Weise zum ersten Mal mit Computergrafik und Programmierung in Berührung.
====

=== Eine virtuelle Schildkröte

Unsere Schildkröte besitzt drei Eigenschaften:

* ihre X-Koordinate
* ihre Y-Koordinate
* ihre Blickrichtung

Zu Beginn steht sie in der Bildschirmmitte und blickt nach rechts.

Jedes Mal, wenn sie vorwärts läuft, berechnen wir ihre neue Position und zeichnen eine Linie.

=== Ein Quadrat zeichnen

Ein Quadrat besteht aus vier gleich langen Linien.

Nach jeder Linie dreht sich die Schildkröte um 90 Grad.

[source]
----
Vorwärts
Rechts drehen

Vorwärts
Rechts drehen

Vorwärts
Rechts drehen

Vorwärts
----

==== Beispielprogramm

[source,basic]
----
CLS

x = MM.HRES / 2
y = MM.VRES / 2

winkel = 0
laenge = 100

FOR i = 1 TO 4

  x2 = x + laenge * COS(RAD(winkel))
  y2 = y + laenge * SIN(RAD(winkel))

  LINE x, y, x2, y2

  x = x2
  y = y2

  winkel = winkel + 90

NEXT i
----

Das Programm berechnet nach jeder Bewegung die neue Position der Schildkröte.

Die Funktion `COS()` bestimmt dabei die horizontale Bewegung, `SIN()` die vertikale Bewegung.

Anschließend wird eine Linie zwischen alter und neuer Position gezeichnet.

=== Experimentiere!

Ändere die Seitenlänge:

[source]
----
laenge = 150
----

oder den Drehwinkel:

[source]
----
winkel = winkel + 60
----

Welche Figur entsteht?

=== Vieleck statt Quadrat

Ersetzen wir den Winkel von 90° durch kleinere Werte, entstehen regelmäßige Vielecke.

Zum Beispiel:

* 120° → Dreieck
* 72° → Fünfeck
* 60° → Sechseck

Je kleiner der Drehwinkel wird, desto mehr Seiten besitzt die Figur.

=== Eine Spirale

Noch spannender wird es, wenn die Schrittlänge nach jeder Bewegung etwas größer wird.

[source,basic]
----
CLS

x = MM.HRES / 2
y = MM.VRES / 2

winkel = 0
laenge = 5

FOR i = 1 TO 80

  x2 = x + laenge * COS(RAD(winkel))
  y2 = y + laenge * SIN(RAD(winkel))

  LINE x, y, x2, y2

  x = x2
  y = y2

  laenge = laenge + 2

  winkel = winkel + 20

NEXT i
----

Mit nur wenigen Zeilen Programmcode entsteht eine beeindruckende Spiralfigur.

=== Warum ist Turtle-Grafik so interessant?

Die Turtle-Grafik verbindet viele Themen, die wir bereits kennengelernt haben:

* Variablen
* Schleifen
* Winkel
* Sinus und Kosinus
* Linien zeichnen

Schon mit wenigen Befehlen lassen sich erstaunlich komplexe Bilder erzeugen.

Viele Fraktale, Sterne, Spiralen oder sogar Schriftarten können nach diesem Prinzip konstruiert werden.

=== Zusammenfassung

In diesem Kapitel hast du die Grundlagen der Grafikprogrammierung mit MMBasic kennengelernt.

Du kennst nun die wichtigsten Grafikbefehle:

* `CLS`
* `PIXEL`
* `LINE`

Außerdem hast du gelernt:

* den Bildschirm zu löschen
* einzelne Pixel zu setzen
* Linien in verschiedenen Farben zu zeichnen
* mit Bildschirmkoordinaten zu arbeiten
* die Bildschirmmitte mit `MM.HRES` und `MM.VRES` zu berechnen
* einfache Zeichnungen aus mehreren Linien zusammenzusetzen
* Grafiken mit Schleifen und Zufallszahlen zu erzeugen
* wie das Konzept der Turtle-Grafik funktioniert
* wie mit Winkeln sowie den Funktionen `SIN()` und `COS()` neue Positionen berechnet werden
* wie sich mit wenigen Befehlen Quadrate, Vielecke und Spiralen zeichnen lassen

Damit verfügst du bereits über alle Grundlagen, um eigene kleine Grafikprogramme zu entwickeln und geometrische Figuren zu zeichnen.

Im nächsten Kapitel erweitern wir diese Möglichkeiten und lernen weitere Grafikbefehle kennen. Damit zeichnen wir Rechtecke, Kreise sowie frei positionierbare Texte und erstellen noch anspruchsvollere Grafiken.
