== Digitale Ein- und Ausgänge

=== Das lernst du

In diesem Kapitel lernst du:

* was digitale Ein- und Ausgänge sind
* wie ein PicoMite Pins steuern kann
* wie Ausgänge ein- und ausgeschaltet werden
* wie Eingänge abgefragt werden
* was die Befehle `SETPIN`, `PIN()` und `GPx` bedeuten
* wie Software mit der Außenwelt kommuniziert

Am Ende des Kapitels kannst du die ersten Hardware-Anschlüsse des PicoMite verwenden.

=== Vom Bildschirm zur Außenwelt

Bisher liefen unsere Programme ausschließlich innerhalb des Computers.

Sie konnten:

* Texte anzeigen
* Grafiken zeichnen
* Dateien speichern
* Spiele ausführen

Nun soll unser Programm mit der Außenwelt kommunizieren.

Der PicoMite besitzt dazu eine Vielzahl von Anschlüssen.

Diese Anschlüsse nennt man:

[source]
----
GPIO Pins
----
oder einfach:

[source]
----
Pins
----

=== Was ist ein Pin?

Ein Pin ist ein elektrischer Anschluss des Mikrocontrollers.

Er kann beispielsweise:

* eine LED einschalten
* einen Taster abfragen
* einen Summer ansteuern
* einen Sensor auslesen

Je nach Konfiguration arbeitet ein Pin als:

* Eingang
* Ausgang

=== Digitale Signale

Digitale Ein- und Ausgänge kennen nur zwei Zustände:

[cols="1,2"]
|===
|Wert |Bedeutung

|0
|Aus

|1
|Ein
|===

Man spricht häufig auch von:

[cols="1,2"]
|===
|Begriff |Bedeutung

|LOW
|0 Volt

|HIGH
|3,3 Volt
|===

Ein digitaler Ausgang kann also lediglich ein- oder ausgeschaltet werden.

=== Ein Ausgang

Ein Ausgang liefert ein elektrisches Signal.

Bevor ein Pin verwendet werden kann, muss seine Funktion festgelegt werden.

Dies geschieht mit:

[source,basic]
----
SETPIN GP0,DOUT
----

Dabei bedeutet:

[cols="1,3"]
|===
|Teil |Bedeutung

|GP0
|Pin GP0

|DOUT
|Digital Output
|===

Der Pin arbeitet nun als digitaler Ausgang.

=== Einen Ausgang einschalten

Nun kann der Ausgang eingeschaltet werden.

[source,basic]
----
PIN(GP0)=1
----

Der Pin liefert jetzt 3,3 Volt.

=== Einen Ausgang ausschalten

[source,basic]
----
PIN(GP0)=0
----

Der Ausgang wird wieder abgeschaltet.

=== Das erste Hardwareprogramm

Dieses Beispiel schaltet einen Ausgang ein.

[source,basic]
----
SETPIN GP0,DOUT

PIN(GP0)=1
----

Das Programm endet anschließend.

Der Ausgang bleibt jedoch eingeschaltet.

=== Einen Ausgang blinken lassen

Interessanter wird es mit einer Schleife.

[source,basic]
----
SETPIN GP0,DOUT

DO

  PIN(GP0)=1

  PAUSE 500

  PIN(GP0)=0

  PAUSE 500

LOOP
----

Der Ausgang wird nun zweimal pro Sekunde umgeschaltet.

=== Was macht PAUSE?

`PAUSE` wartet eine bestimmte Anzahl Millisekunden.

[source,basic]
----
PAUSE 1000
----

entspricht einer Sekunde.

=== Ein Eingang

Ein Eingang empfängt Signale von außen.

Dazu wird der Pin als Eingang konfiguriert.

[source,basic]
----
SETPIN GP1,DIN
----

Das `DIN` steht für:

[source]
----
Digital Input
----

=== Einen Eingang abfragen

Der Zustand eines Eingangs kann mit `PIN()` gelesen werden.

[source,basic]
----
WERT=PIN(GP1)
----

Das Ergebnis ist:

[source]
----
0
oder
1
----

=== Den Zustand anzeigen

[source,basic]
----
SETPIN GP1,DIN

DO

  PRINT PIN(GP1)

  PAUSE 200

LOOP
----

Das Programm zeigt den aktuellen Zustand des Eingangs an.

=== Warum braucht man Eingänge?

Eingänge können beispielsweise mit folgenden Bauteilen verbunden werden:

* Taster
* Schalter
* Bewegungsmelder
* Lichtschranken
* Sensoren

Dadurch kann ein Programm auf Ereignisse reagieren.

=== Ein digitales Modell

Man kann sich einen digitalen Eingang wie eine Frage vorstellen:

[source]
----
Ist etwas aktiv?
Ja oder Nein?
----
oder:

[source]
----
Ist der Taster gedrückt?
Ja oder Nein?
----

Mehr Informationen stehen nicht zur Verfügung.

=== Häufig verwendete Pin-Modi

[cols="1,3"]
|===
|Modus |Bedeutung

|DIN
|Digitaler Eingang

|DOUT
|Digitaler Ausgang

|AIN
|Analoger Eingang

|PWM
|Pulsweitenmodulation

|OFF
|Pin deaktivieren
|===

Weitere Modi werden wir in späteren Kapiteln kennenlernen.

=== Wichtiger Hinweis

Die GPIO-Pins des PicoMite arbeiten mit:

[source]
----
3,3 Volt
----

Höhere Spannungen dürfen nicht direkt angeschlossen werden.

Eine falsche Verdrahtung kann den Mikrocontroller beschädigen.

=== Noch keine Hardware?

Falls du momentan keine Hardware angeschlossen hast, ist das kein Problem.

In den nächsten Kapiteln werden wir konkrete Schaltungen vorstellen.

Bis dahin genügt es, die grundlegenden Befehle kennenzulernen.

=== Experimentiere!

Probiere folgende Änderungen aus:

* Verwende andere GPIO-Pins.
* Ändere die Blinkgeschwindigkeit.
* Gib zusätzliche Texte aus.
* Verwende mehrere Ausgänge gleichzeitig.

=== Probier's selbst!

Versuche folgende Aufgaben:

. Schalte zwei Ausgänge abwechselnd ein.
. Erzeuge ein Lauflicht mit vier Ausgängen.
. Zeige den Zustand eines Eingangs auf dem Bildschirm an.
. Baue eine einfache Blinksteuerung mit unterschiedlichen Zeiten.

=== Zusammenfassung

In diesem Kapitel hast du gelernt:

* was digitale Ein- und Ausgänge sind
* wie Pins konfiguriert werden
* wie Ausgänge geschaltet werden
* wie Eingänge gelesen werden

Damit beginnt ein neuer Abschnitt des Tutorials.

Ab jetzt verlassen wir den Bildschirm und steuern echte Hardware.