== Programme speichern und laden

=== Das lernst du

In diesem Kapitel vertiefst du den Umgang mit Programmen und Dateien.

Du lernst,

* den Unterschied zwischen dem Programmspeicher und gespeicherten Dateien kennen,
* mehrere Programme gleichzeitig zu verwalten,
* Programme sinnvoll zu organisieren und
* einen bewährten Arbeitsablauf für größere Projekte.

=== Warum dieses Kapitel?

In Kapitel 8 hast du bereits gelernt, Programme mit `SAVE` als Datei zu speichern
und mit `LOAD` wieder zu laden.

Für die bisherigen Beispiele war das vollkommen ausreichend.

Mit der Zeit entstehen jedoch mehrere Programme gleichzeitig. Vielleicht
entwickelst du ein Spiel, arbeitest parallel an einem Messprogramm oder möchtest
ältere Versionen deiner Programme aufbewahren.

Jetzt ist der richtige Zeitpunkt, den Umgang mit Programmen und Dateien etwas
genauer kennenzulernen.

=== Programmspeicher und Dateien

Bisher haben wir unsere Programme direkt mit dem integrierten Editor erstellt
und anschließend mit **F1** gespeichert.

Dadurch wird das Programm im Programmspeicher des PicoMite abgelegt. Dieses
Programm bleibt auch nach dem Ausschalten erhalten und kann jederzeit mit `RUN`
gestartet werden.

Zusätzlich kannst du Programme als Dateien speichern. Dadurch lassen sich
beliebig viele Programme archivieren, sichern oder später erneut laden.

[NOTE]
====
Der Programmspeicher enthält immer genau **ein aktuelles Arbeitsprogramm**.

Im Dateisystem können dagegen beliebig viele Programme gespeichert werden.
====

=== Programme speichern

Mit `SAVE` wird das aktuelle Arbeitsprogramm als Datei gespeichert.

[source,basic]
----
SAVE "HANGMAN.BAS"
----

Das Programm befindet sich anschließend sowohl im Programmspeicher als auch als
Datei im Dateisystem.

=== Programme laden

Mit `LOAD` wird eine gespeicherte Datei wieder in den Programmspeicher geladen.

[source,basic]
----
LOAD "HANGMAN.BAS"
----

Danach kannst du das Programm sofort mit `RUN` starten oder weiter bearbeiten.

=== Programme direkt bearbeiten

Statt ein Programm zuerst zu laden, kannst du es auch direkt im Editor öffnen.

[source,basic]
----
EDIT "HANGMAN.BAS"
----

Das spart einen Arbeitsschritt und ist besonders praktisch, wenn du ein
bestehendes Programm ändern möchtest.

=== Programme organisieren

Mit zunehmender Erfahrung wächst auch deine Programmsammlung.

Eine gute Organisation hilft dir dabei, jederzeit den Überblick zu behalten.

==== Aussagekräftige Dateinamen

Verwende möglichst sprechende Dateinamen.

Gut geeignet sind beispielsweise:

* `HANGMAN.BAS`
* `LITTLEPROFESSOR.BAS`
* `REAKTIONSTEST.BAS`

Weniger hilfreich sind Namen wie:

* `TEST.BAS`
* `NEU.BAS`
* `SPIEL1.BAS`

Schon nach kurzer Zeit wirst du Programme anhand ihres Dateinamens schneller
wiederfinden.

==== Sicherheitskopien anlegen

Vor größeren Änderungen empfiehlt es sich, eine Sicherheitskopie anzulegen.

Beispielsweise:

----
PONG_V1.BAS
PONG_V2.BAS
----

So kannst du jederzeit zu einer funktionierenden Version zurückkehren.

==== Ordner verwenden

Bei einer größeren Programmsammlung lohnt es sich, eigene Ordner anzulegen.

Zum Beispiel:

----
/Spiele
/Lernprogramme
/Elektronik
/Experimente
----

Dadurch bleiben deine Projekte dauerhaft übersichtlich.

[TIP]
====
**Programme auf mehrere Dateien aufteilen**

Bei größeren Projekten kann es sinnvoll sein, den Quelltext auf mehrere
Dateien zu verteilen. So lassen sich beispielsweise Grafikroutinen,
Hilfsfunktionen oder die Spiellogik in getrennten Dateien verwalten.

MMBasic unterstützt dies über `#INCLUDE` in Verbindung mit `CMM2 LOAD` bzw.
`CMM2 RUN`.

Diese Funktion stammt ursprünglich vom Colour Maximite 2 und wird vor allem
für größere Projekte oder zur Portierung von CMM2-Programmen verwendet.

Für die meisten PicoMite-Projekte reicht jedoch ein einzelnes Programm oder
eine Library völlig aus.
====

=== Wiederverwendbare Programmteile

In größeren Projekten werden bestimmte Unterprogramme und Funktionen häufig
mehrfach benötigt.

Vielleicht hast du beispielsweise Routinen geschrieben, die

* Texte auf dem Bildschirm positionieren,
* Messwerte umrechnen,
* Eingaben überprüfen oder
* wiederkehrende Berechnungen durchführen.

Du könntest diese Routinen in jedes neue Programm kopieren. Das wird jedoch
schnell unübersichtlich. Außerdem müsstest du Fehlerkorrekturen anschließend
in allen Kopien nachtragen.

MMBasic bietet dafür eine Library. Darin gespeicherte Routinen stehen allen
Programmen zur Verfügung und können wie eingebaute Befehle oder Funktionen
verwendet werden.

==== Eine Library-Routine erstellen

Library-Routinen werden zunächst wie gewöhnliche Bestandteile eines
MMBasic-Programms geschrieben und getestet.

Ein einfaches Beispiel:

[source,basic]
----
SUB Begruessung
  PRINT "Willkommen bei MMBasic!"
END SUB

FUNCTION Quadrat(Zahl)
  Quadrat = Zahl * Zahl
END FUNCTION
----

Teste die Routinen zunächst mit einem kleinen Hauptprogramm:

[source,basic]
----
Begruessung
PRINT "Das Quadrat von 7 ist"; Quadrat(7)

SUB Begruessung
  PRINT "Willkommen bei MMBasic!"
END SUB

FUNCTION Quadrat(Zahl)
  Quadrat = Zahl * Zahl
END FUNCTION
----

Wenn alles fehlerfrei funktioniert, speicherst du den Quelltext zuerst als
normale BASIC-Datei:

[source,basic]
----
SAVE "MEINELIB.BAS"
----

Danach überträgst du den Inhalt des Programmspeichers mit

[source,basic]
----
LIBRARY SAVE
----

in die Library.

MMBasic komprimiert den Quelltext und speichert ihn in einem besonderen
Bereich des Flash-Speichers. Anschließend wird der normale Programmspeicher
geleert.

[IMPORTANT]
====
Speichere den Quelltext vor `LIBRARY SAVE` immer zusätzlich als normale
BASIC-Datei.

Beim Übertragen in die Library entfernt MMBasic unter anderem Kommentare,
Leerzeilen und überflüssige Leerzeichen. Die Library ist deshalb nicht als
Ersatz für die ursprüngliche Quelltextdatei gedacht.
====

==== Library-Routinen verwenden

Nach dem Speichern stehen die Routinen allen BASIC-Programmen zur Verfügung.

Ein neues Programm kann sie direkt aufrufen:

[source,basic]
----
Begruessung

PRINT "Das Quadrat von 12 ist"; Quadrat(12)
----

Die Definitionen von `Begruessung` und `Quadrat` müssen nicht mehr im
Hauptprogramm enthalten sein.

Die Routinen bleiben auch dann erhalten, wenn du mit `NEW` den
Programmspeicher löschst oder ein anderes Programm lädst.

Du kannst sie sogar direkt an der Eingabeaufforderung verwenden:

[source,basic]
----
PRINT Quadrat(9)
----

MMBasic behandelt Library-Routinen damit fast wie zusätzliche Bestandteile
der Programmiersprache.

==== Die Library erweitern

Du kannst `LIBRARY SAVE` mehrfach verwenden.

Bei jedem Aufruf wird der aktuelle Inhalt des Programmspeichers an die
bereits vorhandene Library angehängt.

So kannst du deine Library schrittweise um weitere Routinen ergänzen.

[CAUTION]
====
Achte darauf, keine Routinen mit bereits verwendeten Namen erneut
hinzuzufügen. Da die neuen Bestandteile an die vorhandene Library angehängt
werden, solltest du deine Library sorgfältig planen und den vollständigen
Quelltext aufbewahren.
====

==== Inhalt der Library anzeigen

Mit

[source,basic]
----
LIBRARY LIST
----

kannst du dir den Inhalt der Library anzeigen lassen.

Bei einem normalen

[source,basic]
----
LIST
----

werden die Library-Routinen dagegen nicht angezeigt. `LIST` zeigt nur das
aktuell geladene Hauptprogramm.

==== Library sichern und wiederherstellen

Die gesamte Library kann als Datei gesichert werden:

[source,basic]
----
LIBRARY DISK SAVE "MEINELIB.LIB"
----

Mit

[source,basic]
----
LIBRARY DISK LOAD "MEINELIB.LIB"
----

kannst du sie später wiederherstellen.

Diese Sicherung ist beispielsweise nützlich, wenn du die Firmware
aktualisieren oder dieselbe Library auf einem anderen PicoMite verwenden
möchtest.

==== Library löschen

Mit

[source,basic]
----
LIBRARY DELETE
----

wird die gesamte Library gelöscht.

Der dafür verwendete Flash-Speicher steht anschließend wieder für normale
Programme zur Verfügung.

[NOTE]
====
Die Library verwendet den Flash-Slot 3. Solange eine Library installiert
ist, kann dieser Slot nicht zum Speichern eines normalen Programms verwendet
werden.
====

==== Was kann eine Library enthalten?

Eine Library kann mehr als nur `SUB`- und `FUNCTION`-Routinen enthalten.

Möglich sind unter anderem:

* Unterprogramme,
* Funktionen,
* eingebettete C-Routinen,
* eingebettete Fonts und
* Initialisierungscode.

Für den Einstieg sind wiederverwendbare Unterprogramme und Funktionen jedoch
am wichtigsten.

=== Automatisch ausgeführter Library-Code

Eine Library kann auch Anweisungen enthalten, die sich nicht innerhalb einer
`SUB` oder `FUNCTION` befinden.

Solcher Code wird automatisch ausgeführt, bevor ein Programm mit `RUN`
gestartet wird.

Damit können beispielsweise Konstanten bereitgestellt werden:

[source,basic]
----
CONST TRUE = 1
CONST FALSE = 0
----

Nach dem Speichern in der Library stehen `TRUE` und `FALSE` allen
Programmen zur Verfügung.

[NOTE]
====
Initialisierungscode in der Library wird vor jedem mit `RUN` gestarteten
Programm ausgeführt.

Er ist nicht mit der besonderen Routine `MM.STARTUP` zu verwechseln, die nur
beim Einschalten oder Zurücksetzen des PicoMite ausgeführt wird.
====

==== Besondere Systemroutinen

MMBasic kennt einige besondere Namen für Unterprogramme.

`MM.STARTUP`::
Wird einmal nach dem Einschalten oder einem Reset ausgeführt. Damit kann
beispielsweise eine angeschlossene Echtzeituhr eingelesen werden.

[source,basic]
----
SUB MM.STARTUP
  RTC GETTIME
END SUB
----

[CAUTION]
====
Verwende `MM.STARTUP` nicht zur allgemeinen Vorbereitung eines später mit
`RUN` gestarteten Programms, beispielsweise zum Dimensionieren von Arrays
oder zum Öffnen von Kommunikationskanälen.

Beim Start mit `RUN` setzt MMBasic den Zustand des Interpreters für einen
neuen Programmlauf zurück. Solche Vorbereitungen gehören deshalb in den
normalen Initialisierungsteil des Hauptprogramms oder in den automatisch vor
`RUN` ausgeführten Library-Code.
====

`MM.PROMPT`::
Wird anstelle der normalen Eingabeaufforderung ausgeführt. Damit lässt sich
beispielsweise eine eigene Eingabeaufforderung anzeigen.

[source,basic]
----
SUB MM.PROMPT
  PRINT TIME$ "> ";
END SUB
----

`MM.END`::
Wird ausgeführt, wenn ein Programm durch `END` oder durch das Erreichen des
Programmendes beendet wird.

Diese Routinen sind für besondere Anwendungen gedacht. Für gewöhnliche
Initialisierungen innerhalb eines Programms ist weiterhin normaler
Programmcode besser geeignet.

=== Ein typischer Arbeitsablauf

Viele MMBasic-Anwender arbeiten nach einem einfachen Schema:

----
EDIT
 ↓
Programm entwickeln
 ↓
F1
 ↓
RUN
 ↓
SAVE "MEINPROGRAMM.BAS"
----

Zu einem späteren Zeitpunkt:

----
LOAD "MEINPROGRAMM.BAS"
 ↓
EDIT
 ↓
Programm erweitern
 ↓
F1
 ↓
RUN
----

Dieser Arbeitsablauf hat sich in der Praxis sehr bewährt.

=== Profitipps

[TIP]
====
**Programme automatisch starten**

Soll dein Programm nach jedem Einschalten des PicoMite automatisch gestartet
werden, kannst du dies mit folgendem Befehl aktivieren:

[source,basic]
----
OPTION AUTORUN ON
----

Während der Entwicklung empfiehlt es sich, diese Funktion zunächst deaktiviert
zu lassen und Programme manuell mit `RUN` zu starten.

Mit

[source,basic]
----
OPTION AUTORUN OFF
----

wird der automatische Start wieder abgeschaltet.
====

[TIP]
====
**Programme regelmäßig sichern**

Speichere wichtige Programme zusätzlich auf deinem PC oder in einem Cloud-Speicher.
Eine SD-Karte kann verloren gehen oder beschädigt werden.
====

[TIP]
====
**Ordnung spart Zeit**

Eine sinnvolle Ordnerstruktur und aussagekräftige Dateinamen helfen dir, auch
bei vielen Projekten den Überblick zu behalten.
====

=== Zusammenfassung

Du kennst nun den Unterschied zwischen dem Programmspeicher des PicoMite und
Programmen, die als Dateien gespeichert werden.

Außerdem weißt du, wie du Programme sinnvoll organisierst, Sicherheitskopien
anlegst und mehrere Projekte gleichzeitig verwaltest.

Mit diesen Techniken behältst du auch bei größeren BASIC-Projekten jederzeit
den Überblick.
