== Dateiverwaltung auf der SD-Karte

=== Das lernst du

In diesem Kapitel lernst du:

* Verzeichnisse anzulegen
* zwischen Verzeichnissen zu wechseln
* Dateien umzubenennen
* Dateien zu kopieren
* Dateien zu lГ¶schen
* eine sinnvolle Projektstruktur aufzubauen

Am Ende des Kapitels kannst du auch grГ¶Гҹere Projekte Гјbersichtlich organisieren.

=== Warum Verzeichnisse?

Im vorherigen Kapitel hast du gelernt, Programme sinnvoll zu organisieren und
mit `SAVE` und `LOAD` zu verwalten.

Sobald mehrere Projekte entstehen, reicht es jedoch nicht mehr aus, alle
Dateien in einem einzigen Verzeichnis abzulegen.

Mit Verzeichnissen kannst du deine Programme thematisch ordnen und behГӨltst
auch bei einer grГ¶Гҹeren Programmsammlung den Гңberblick.

Beispiel:

[source]
----
PONG.BAS
----

Mit zunehmender Erfahrung entstehen jedoch immer mehr Programme.

Beispielsweise:

[source]
----
PONG.BAS
SENSO.BAS
AMPEL.BAS
UHR.BAS
TEST.BAS
----

Irgendwann wird es schwierig, den Гңberblick zu behalten.

Deshalb bieten PicoMite und Colour Maximite 2 Verzeichnisse an.

=== Eine sinnvolle Projektstruktur

Ein mГ¶glicher Aufbau kГ¶nnte so aussehen:

[source]
----
/
в”ңв”Җв”Җ SPIELE
в”Ӯ   в”ңв”Җв”Җ PONG.BAS
в”Ӯ   в””в”Җв”Җ SENSO.BAS
в”Ӯ
в”ңв”Җв”Җ LERNPROGRAMME
в”Ӯ   в”ңв”Җв”Җ HANGMAN.BAS
в”Ӯ   в””в”Җв”Җ LITTLEPROFESSOR.BAS
в”Ӯ
в”ңв”Җв”Җ ELEKTRONIK
в”Ӯ   в”ңв”Җв”Җ AMPEL.BAS
в”Ӯ   в””в”Җв”Җ UHR.BAS
в”Ӯ
в””в”Җв”Җ TEST
----

Dadurch bleiben Programme Гјbersichtlich organisiert.

[TIP]
====
Bei grГ¶Гҹeren Projekten kГ¶nnen Programme auch auf mehrere Quelldateien
aufgeteilt werden.

MMBasic unterstГјtzt dies Гјber `#INCLUDE` in Verbindung mit `CMM2 LOAD`
oder `CMM2 RUN`.

Diese Funktion eignet sich vor allem fГјr umfangreiche Projekte und zur
Portierung von Colour-Maximite-2-Programmen.
====

=== Verzeichnisse anlegen

Mit MKDIR wird ein neues Verzeichnis erstellt.

Beispiel:

[source,basic]
----
MKDIR "SPIELE"
----

Danach existiert das neue Verzeichnis:

[source]
----
SPIELE
----

=== Verzeichnis wechseln

Mit CHDIR wird das aktuelle Arbeitsverzeichnis geГӨndert.

Beispiel:

[source,basic]
----
CHDIR "SPIELE"
----

Alle folgenden Dateibefehle beziehen sich nun auf dieses Verzeichnis.

=== Das aktuelle Verzeichnis

Auf beiden Plattformen gibt es spezielle Verzeichnisnamen:

[cols="1,3"]
|===
|Eintrag |Bedeutung

|.
|Aktuelles Verzeichnis

|..
|Eine Ebene nach oben

|/
|Wurzelverzeichnis
|===

=== Zum Hauptverzeichnis zurГјckkehren

Mit:

[source,basic]
----
CHDIR "/"
----

wechselst du zurГјck in das Wurzelverzeichnis.

=== Eine Ebene nach oben

Mit:

[source,basic]
----
CHDIR ".."
----

wechselst du in das Гјbergeordnete Verzeichnis.

Beispiel:

[source]
----
/
в””в”Җв”Җ SPIELE
    в””в”Җв”Җ PONG.BAS
----

Befindest du dich in:

[source]
----
/SPIELE
----

fГјhrt:

[source,basic]
----
CHDIR ".."
----

zurГјck nach:

[source]
----
/
----

=== Dateien umbenennen

Mit RENAME kann eine Datei einen neuen Namen erhalten.

Beispiel:

[source,basic]
----
RENAME "PONG.BAS" AS "PONG_V1.BAS"
----

Danach heiГҹt die Datei:

[source]
----
PONG_V1.BAS
----

=== Dateien verschieben

RENAME kann gleichzeitig zum Verschieben verwendet werden.

Beispiel:

[source,basic]
----
RENAME "PONG.BAS" AS "/SPIELE/PONG.BAS"
----

Die Datei wird dabei in das Verzeichnis SPIELE verschoben.

=== Dateien kopieren

Mit COPY wird eine Datei dupliziert.

Beispiel:

[source,basic]
----
COPY "PONG.BAS" TO "PONG_ALT.BAS"
----

Danach existieren beide Dateien:

[source]
----
PONG.BAS
PONG_ALT.BAS
----

=== Warum Kopien sinnvoll sind

Vor grГ¶Гҹeren Г„nderungen kann eine Sicherheitskopie erstellt werden.

Beispiel:

[source,basic]
----
COPY "SENSO.BAS" TO "SENSO_BAK.BAS"
----

Falls etwas schiefgeht, steht die ursprГјngliche Version weiterhin zur VerfГјgung.

=== Dateien lГ¶schen

Mit KILL wird eine Datei gelГ¶scht.

Beispiel:

[source,basic]
----
KILL "TEST.BAS"
----

Danach ist die Datei nicht mehr vorhanden.

[WARNING]
====
GelГ¶schte Dateien kГ¶nnen in der Regel nicht wiederhergestellt werden.

Verwende KILL deshalb mit Vorsicht.
====

=== Verzeichnisse lГ¶schen

Mit RMDIR wird ein Verzeichnis entfernt.

Beispiel:

[source,basic]
----
RMDIR "TEST"
----

Das Verzeichnis muss leer sein.

Existieren darin noch Dateien, wird eine Fehlermeldung erzeugt.

=== Beispielprojekt anlegen

Erstellen wir eine kleine Projektstruktur:

[source,basic]
----
MKDIR "SPIELE"
MKDIR "PROJEKTE"
MKDIR "TEST"
----

Danach kГ¶nnte die Struktur so aussehen:

[source]
----
/
в”ңв”Җв”Җ SPIELE
в”ңв”Җв”Җ PROJEKTE
в””в”Җв”Җ TEST
----

=== Dateien organisieren

Wechseln wir zunГӨchst in das Verzeichnis SPIELE:

[source,basic]
----
CHDIR "SPIELE"
----

Nun speichern wir dort beispielsweise:

[source,basic]
----
SAVE "PONG.BAS"
SAVE "SENSO.BAS"
----

Die Programme bleiben dadurch sauber von anderen Projekten getrennt.

=== VollstГӨndige Pfadangaben

Dateibefehle kГ¶nnen auch mit vollstГӨndigen Pfaden verwendet werden.

Beispiel:

[source,basic]
----
LOAD "/SPIELE/PONG.BAS"
----

oder:

[source,basic]
----
COPY "/SPIELE/PONG.BAS" TO "/TEST/PONG.BAS"
----

Dies ist besonders praktisch bei grГ¶Гҹeren Projekten.

=== PicoMite und Colour Maximite 2

Die meisten Verzeichnisbefehle funktionieren auf beiden Plattformen nahezu identisch.

Dazu gehГ¶ren:

* CHDIR
* MKDIR
* RMDIR
* COPY
* RENAME
* KILL

Dadurch lassen sich Projekte leicht zwischen PicoMite und Colour Maximite 2 Гјbertragen.

=== Tipps aus der Praxis

* Verwende fГјr jedes Projekt ein eigenes Verzeichnis.
* Lege wiederverwendbare Bibliotheken getrennt von deinen Projekten ab.
* Sichere wichtige Projekte regelmГӨГҹig auf deinem PC.
* Verwende keine Leerzeichen in Dateinamen.
* Halte Verzeichnisnamen mГ¶glichst kurz und eindeutig.
* Verwende aussagekrГӨftige Dateinamen.
* Erstelle vor grГ¶Гҹeren Г„nderungen Sicherheitskopien.
* LГ¶sche Dateien erst, wenn du sicher bist, dass sie nicht mehr benГ¶tigt werden.
* Halte die Verzeichnisstruktur mГ¶glichst einfach.

=== Probier's selbst!

Versuche folgende Aufgaben:

. Erstelle ein Verzeichnis SPIELE.
. Wechsle in dieses Verzeichnis.
. Speichere dort ein kleines Testprogramm.
. Erstelle eine Sicherheitskopie mit COPY.
. Benenne die Kopie um.
. LГ¶sche die Kopie wieder.
. Wechsle zurГјck ins Wurzelverzeichnis.

=== Zusammenfassung

In diesem Kapitel hast du gelernt:

* Verzeichnisse mit MKDIR anzulegen
* mit CHDIR zwischen Verzeichnissen zu wechseln
* Dateien mit COPY zu kopieren
* Dateien mit RENAME umzubenennen
* Dateien mit KILL zu lГ¶schen
* Verzeichnisse mit RMDIR zu entfernen

Mit diesen Befehlen kannst du auch grГ¶Гҹere MMBasic-Projekte Гјbersichtlich organisieren und verwalten.

Mit einer guten Verzeichnisstruktur lassen sich auch umfangreiche Projekte
Гјbersichtlich verwalten.

Im nГӨchsten Kapitel lernst du mit `CHAIN` eine MГ¶glichkeit kennen,
mehrere Programme miteinander zu verbinden.
